### ISSUE TITLE
ClassCastException: net.minecraft.block.BlockAir cannot be cast to com.thefjong.gravestone.blocks.BlockGravestone

### ISSUE THREAD

**Issue by Sasikaa** [TheFjonG/Gravestone#1]
I died hostile mobs, in the air...

This is my crash log:
http://pastebin.com/VQVWXtpm

if you not repair this, not using the mod in the modpack...

**Comment by TheFjonG** [comment]
Im sorry, Ill fix this right away.

A fix will be up later today :)

Thank you!

**Comment by TheFjonG** [comment]
This bug have been fixed in version 1.0.1
